Order id is 210310000130772 and order Variety is co
Order id is 210310000130793 and order Variety is co
Order id is 210310000130797 and order Variety is co
unable to delete order id :  210310000130797
Order id is 210310000131001 and order Variety is co
Order id is 210310000965162 and order Variety is regular
Order id is 210310000965238 and order Variety is regular
Order id is 210310002044263 and order Variety is regular
Order id is 210310000130797 and order Variety is co
unable to delete order id :  210310000130797
Order id is 210310000130797 and order Variety is co
unable to delete order id :  210310000130797
Order id is 210310000130797 and order Variety is co
unable to delete order id :  210310000130797
Order id is 210310000130797 and order Variety is co
unable to delete order id :  210310000130797
Going to close position for NIFTY2131015200CE in NSE
Quantities for buy to be placed 75
Traceback (most recent call last):
  File "square_off.py", line 96, in <module>
  File "square_off.py", line 32, in placeMarketOrder
    transaction_type=t_type,
  File "/Users/saravana.kumar/opt/anaconda3/envs/algo/lib/python3.8/site-packages/kiteconnect/connect.py", line 346, in place_order
    return self._post("order.place", params)["order_id"]
  File "/Users/saravana.kumar/opt/anaconda3/envs/algo/lib/python3.8/site-packages/kiteconnect/connect.py", line 821, in _post
    return self._request(route, "POST", params)
  File "/Users/saravana.kumar/opt/anaconda3/envs/algo/lib/python3.8/site-packages/kiteconnect/connect.py", line 886, in _request
    raise exp(data["message"], code=r.status_code)
kiteconnect.exceptions.InputException: Unknown `tradingsymbol`.
